plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bhimmondal.fightclub'
    compileSdk 35

    defaultConfig {
        applicationId "com.bhimmondal.fightclub"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
